// Generated by https://quicktype.io

export interface NasaPaginatedResponse {
    collection: Collection;
}

export interface Collection {
    version:  string;
    href:     string;
    items:    Item[];
    metadata: Metadata;
    links:    CollectionLink[];
}

export interface Item {
    href:  string;
    data:  Datum[];
    links: ItemLink[];
}

export interface Datum {
    center:             Center;
    title:              string;
    nasa_id:            string;
    media_type:         MediaType;
    keywords:           string[];
    date_created:       string;
    description:        string;
    description_508?:   string;
    secondary_creator?: string;
    location?:          Location;
    album?:             string[];
    photographer?:      Location;
}

export interface MyItems extends Item {
    index: string;
    linkBueno: string;
    title: string;
    description: string;
    date_created: string;
    keywords: string[],
    nasa_id: string
}

export enum Center {
    Grc = "GRC",
    Gsfc = "GSFC",
    Jpl = "JPL",
}

export enum Location {
    GreenbeltMD = "Greenbelt, MD",
    NASAGlennResearchCenter = "NASA Glenn Research Center",
}

export enum MediaType {
    Image = "image",
}

export interface ItemLink {
    href:   string;
    rel:    Rel;
    render: MediaType;
}

export enum Rel {
    Preview = "preview",
}

export interface CollectionLink {
    rel:    string;
    prompt: string;
    href:   string;
}

export interface Metadata {
    total_hits: number;
}
